### ISSUE TITLE
association fields in md.json

### ISSUE THREAD

**Issue by IrenH** [clld/dictionaria#27]
we need to find a way to specify association fields in the md.json (e.g. \syn, \cf, etc)

**Comment by xrotwang** [comment]
I propose to go with a whitelist approach, i.e. declare a fixed set of markers as association fields, possibly following the [MDF spec](http://www-01.sil.org/computing/shoebox/MDF_AppendixB.html). If we would allow custom defintions of association fields, we'd also need a way to specifiy labels for the inverse relation (since we also want to link back).

Currently, this whitelist would include `cf`, `mn`, `sy`, `an`, and we'd have "main entry" and "subentry" as label and inverse label for `mn`.

**Comment by IrenH** [comment]
sounds good, the label for cf should be "see also" synonym and antonym do not need inverse lables, while other relations will: e.g. contains vs part of

**Comment by xrotwang** [comment]
So our whitelist of relations between entries currently looks as follows:
- `cf`: rendered as *see also*
- `mn`: rendered as *see main entry*
- `sy`: rendered as *synonym*
- `an`: rendered as *antonym*

The corresponding column names in the CLDF input could be the marker names prefixed with `rel_`.

**Comment by IrenH** [comment]
This is good and easy enough to use... we may have to add some more, like "related via root" (similar to main entry, i guess), or ...is part of... and ...contains...

**Comment by xrotwang** [comment]
Either done or obsolete.
