### ISSUE TITLE
only display comparison meaning once

### ISSUE THREAD

**Issue by IrenH** [clld/dictionaria#29]
e.g. http://dictionaria.clld.org/units/daakaka-46-1

the comparison meaning listed after the semse looks odd, does it need to be displayed here?

**Comment by xrotwang** [comment]
Well, the comparison meaning listed after the sense is the content of `\re`. This marker belongs to the sense, so it needs to be put somewhere around where it is now. The comparison meaning listed above is the match with concepticon.
As far as I understood, at some point the concepticon matches should solely be derived from the `\re` fields, so once we have this in place, there will only be the sense-specific comparison meaning, which will be linked if possible and only text otherwise.

**Comment by IrenH** [comment]
but in this case you created the \re fields out of concepticon, so they should not be displayed at all.

**Comment by xrotwang** [comment]
No, they should be manually corrected and put into whatever fieldname Martin proposed. So, if in that field (I forgot what marker was proposed) I find a concepticon ID in square brackets, this will be used as concepticon comparison meaning.

**Comment by IrenH** [comment]
i.e. I have to do what exactly in this case? I look at each \re field und check whether it fits, if it does, I copy it into the whatsitcalled field together with the ID in square brackets and delete the definition in double quotes, then I delete the content of \re... 
OR: I check the contens of \re delete either the definition in double qoutes and leave the rest (concepticon word and ID) if it fits, and if it doesn't I delete the whoel content of \re, when I am doen with all \re's I rename them all into the whateveritiscalled field?

**Comment by xrotwang** [comment]
`\re` is for non-concepticon comparison meanings. `\zcom2` is the field I will inspect for concepticon matches. In `\zcom2` only numbers in square brackets matter, so the definition can be left in there as well.

So in the Daakaka case, where there are no `\re` values provided by the author, both approaches outlined by you are equivalent. Only in cases where there are author-supplied `\re` values the second approach will not work.

**Comment by IrenH** [comment]
I think in this case the author did not proide any \re contents, so I will go with the 2nd approach :)
