### ISSUE TITLE
undisplay concepticon descriptions 

### ISSUE THREAD

**Issue by IrenH** [clld/dictionaria#47]
...from here:
http://dictionaria.clld.org/parameters

instead put representation column in second place and maybe differentiate in there by language?
e.g. 2: Daakaka (1), Hdi (1)

**Comment by xrotwang** [comment]
Why should we not display the concepticon descriptions? They are supposed to describe the meaning more precisely. If they fail to do so, this should be fixed in Concepticon - but fixing these things will be more probable if they are exposed to a wider public. So maybe we should rather add a link to [concepticon issues](https://github.com/clld/concepticon-data/issues)?
