### ISSUE TITLE
Updating clld breaks `initializedb.py`

### ISSUE THREAD

**Issue by johenglisch** [clld/dictionaria#94]
It seems to be related to the new template system introduced in version 7?  Several imports are broken and I couldn't find the `initializedb()` function, which adds the custom command-line arguments (like `--internal`)…

Workaround:  Locking clld (and dependencies) to a lower version.

    clld>=4.7,<7.0.0
    clld-glottologfamily-plugin>=2.0.0,<4.0.0

**Comment by xrotwang** [comment]
Ah, sorry. I guess I forgot about dictionaria. (But hey, it's a new major version, so breakage allowed :) ).
Upgrading shouldn't be too difficult, though. There are two options - I think:
- Use the generic `clld initdb` command - and get what used to be cli options in the function, e.g. using `input`.
- Adding a `dictionaria-app` cli.

Since db initialization is typically something explicitly done by humans, I'd opt for (the simpler) first option.

**Comment by xrotwang** [comment]
[clld initdb](https://github.com/clld/clld/blob/master/src/clld/commands/initdb.py) calls `initializedb.main` and `prime_cache` as it used to be - but `args` will be a bit different.
